import type { Resident } from '../types';

export const MOCK_RESIDENTS: Resident[] = [
  {
    id: '1',
    first_name: 'Maria',
    last_name: 'Santos',
    age: 68,
    sex: 'Female',
    address: 'Zone 1, Santa Rosa',
    is_senior: true,
    is_pwd: false,
    is_pregnant: false,
    is_child: false,
    risk_score: 85,
    risk_level: 'High',
    last_visit: '2025-12-01',
    conditions: ['Hypertension', 'Diabetes'],
    recent_symptoms: ['Dizziness', 'Dizziness', 'Headache'],
    follow_up_required: true,
    created_at: new Date().toISOString()
  },
  {
    id: '2',
    first_name: 'Juan',
    last_name: 'Dela Cruz',
    age: 45,
    sex: 'Male',
    address: 'Zone 3, San Pedro',
    is_senior: false,
    is_pwd: true,
    is_pregnant: false,
    is_child: false,
    risk_score: 45,
    risk_level: 'Medium',
    last_visit: '2025-11-20',
    conditions: [],
    recent_symptoms: [],
    follow_up_required: false,
    created_at: new Date().toISOString()
  },
  {
    id: '3',
    first_name: 'Elena',
    last_name: 'Reyes',
    age: 28,
    sex: 'Female',
    address: 'Zone 2, Poblacion',
    is_senior: false,
    is_pwd: false,
    is_pregnant: true,
    is_child: false,
    risk_score: 60,
    risk_level: 'Medium',
    last_visit: '2025-12-12',
    conditions: ['Asthma'],
    recent_symptoms: ['Difficulty Breathing'],
    follow_up_required: true,
    created_at: new Date().toISOString()
  },
  {
    id: '4',
    first_name: 'Pedro',
    last_name: 'Garcia',
    age: 72,
    sex: 'Male',
    address: 'Zone 4, Riverside',
    is_senior: true,
    is_pwd: false,
    is_pregnant: false,
    is_child: false,
    risk_score: 20,
    risk_level: 'Low',
    last_visit: '2025-10-15',
    conditions: ['Hypertension'],
    recent_symptoms: [],
    follow_up_required: false,
    created_at: new Date().toISOString()
  }
];
